/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BlockComment: typeof import('./src/components/UIElements/BlockComment.vue')['default']
    Card: typeof import('./src/components/UIElements/Card.vue')['default']
    Comment: typeof import('./src/components/UIElements/Comment.vue')['default']
    Comments: typeof import('./src/components/UIElements/Comments.vue')['default']
    Content: typeof import('./src/components/Content.vue')['default']
    DownloadTor: typeof import('./src/components/UIElements/DownloadTor.vue')['default']
    Empty: typeof import('./src/components/UIElements/Empty.vue')['default']
    Emty: typeof import('./src/components/UIElements/Emty.vue')['default']
    Error404: typeof import('./src/components/UIElements/Error404.vue')['default']
    Filter: typeof import('./src/components/UIElements/Filter.vue')['default']
    Header: typeof import('./src/components/Layout/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Info: typeof import('./src/components/UIElements/Info.vue')['default']
    InfoBlock: typeof import('./src/components/UIElements/InfoBlock.vue')['default']
    InfoHeader: typeof import('./src/components/Layout/InfoHeader.vue')['default']
    List: typeof import('./src/components/Layout/List.vue')['default']
    Loading: typeof import('./src/components/UIElements/Loading.vue')['default']
    MediaPlayer: typeof import('./src/components/UIElements/MediaPlayer.vue')['default']
    ModalSearch: typeof import('./src/components/Layout/modalSearch.vue')['default']
    Navbar: typeof import('./src/components/Layout/Navbar.vue')['default']
    Pagination: typeof import('./src/components/UIElements/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Schedule: typeof import('./src/components/Layout/Schedule.vue')['default']
    SMCard: typeof import('./src/components/UIElements/SMCard.vue')['default']
    Switch: typeof import('./src/components/UIElements/Switch.vue')['default']
  }
}
